name: CD

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release
    uses:  ./.github/workflows/release.yml
    secrets: inherit

  deploy:
    name: Production
    needs: release
    if: ${{ needs.release.outputs.released }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
